### ISSUE TITLE
Translation sync not running for server repositories

### ISSUE THREAD

**Issue by PVince81** [owncloud/translation-sync#24]
Not sure if this is related to the Drone migration, but it seems the last transifex commits were from around September 10/12th.

We also did not see any sync results in https://drone.owncloud.com/owncloud/translation-sync/

@tboerger can you have a look ?

cc @phil-davis who helped investigate

**Comment by PVince81** [comment]
refs:
- last core commit from transifex: https://github.com/owncloud/core/commit/a0fd679ede3f34fe23feba3ee393884e8caf9340 (september 12th)
- last phoenix commit from transifex: https://github.com/owncloud/phoenix/commit/bcccf9ced85d41add1027bf20bd06ba1d97c7103 (september 10th)

**Comment by PVince81** [comment]
cc @DeepDiver1975 FYI

**Comment by PVince81** [comment]
Idea for later: add some monitoring for the core repo that detects whenever the last transifex commit is too old.

**Comment by PVince81** [comment]
attempt by @dschmidt here https://github.com/owncloud/translation-sync/pull/25

**Comment by dschmidt** [comment]
PR works. Even has the four repos from mobile branch incorporated and making the branch obsolete that way. 

Full run was succesful, so commits have shown up in repos ;-) Needs to be merged before the nightly run will make use of it.

**Comment by PVince81** [comment]
outdated, likely already resolved
