### ISSUE TITLE
phoenix translation sync failing

### ISSUE THREAD

**Issue by phil-davis** [owncloud/translation-sync#35]
The last 4 nights the sync for phoenix has failed, e.g.
https://drone.owncloud.com/owncloud/translation-sync/1549/33/5

```
tx INFO: Pushing source file (template.pot)
tx ERROR: Could not upload source file. You can use --skip to ignore this error and continue the execution.
tx ERROR: [Errno 2] No such file or directory: '/drone/src/phoenix/l10n/template.pot'
make: *** [l10n-push] Error 1
Makefile:81: recipe for target 'l10n-push' failed
```

**Comment by phil-davis** [comment]
@DeepDiver1975 or @dschmidt maybe you will know what changed a few days ago?

**Comment by phil-davis** [comment]
Still failing every night, e.g. https://drone.owncloud.com/owncloud/translation-sync/1558/33/5

@micbar who can look at this?

**Comment by phil-davis** [comment]
Still failing: https://drone.owncloud.com/owncloud/translation-sync/1562/33/5

@DeepDiver1975 do you know about this? Or who should look at it?

**Comment by DeepDiver1975** [comment]
Please talk to the phoenix team

![Screenshot from 2020-06-15 09-50-06](https://user-images.githubusercontent.com/1005065/84631418-a233b000-aeed-11ea-81b6-430f49c7515f.png)

**Comment by DeepDiver1975** [comment]
There is something wrong with the code base

**Comment by phil-davis** [comment]
I raised issue https://github.com/owncloud/phoenix/issues/3603 so that somebody might notice.
