### ISSUE TITLE
CI fails for files_mediaviewer

### ISSUE THREAD

**Issue by phil-davis** [owncloud/translation-sync#43]
For example: https://drone.owncloud.com/owncloud/translation-sync/2014/16/4
```
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/drone/src/files_mediaviewer/node_modules/which/which.js:13:12)
```

**Comment by phil-davis** [comment]
The first fail is https://drone.owncloud.com/owncloud/translation-sync/2010/16/4
2021-07-01 19:01

"something happened" around 2021-06-30 or 2021-07-01.

**Comment by phil-davis** [comment]
These were merged in owncloudci/transifex on 2021-07-01:
https://github.com/owncloud-ci/transifex/pull/33
https://github.com/owncloud-ci/transifex/pull/34

I guess one of those dependency changes is related?

**Comment by phil-davis** [comment]
@micbar who looks at this sort of stuff?

**Comment by micbar** [comment]
needs to be mentioned on monday morning :-)

**Comment by JanAckermann** [comment]
Indeed node-sass requires at least v6.0 to run with ode 16 
https://github.com/sass/node-sass

**Comment by JanAckermann** [comment]
Let's see what will happen during the night, if ci will be green, we can close this issue.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/translation-sync/2015/16/1
Passed - so this is fixed.
