### ISSUE TITLE
templateeditor repo discontinued

### ISSUE THREAD

**Issue by S-Panta** [owncloud/translation-sync#58]
Related PR :https://github.com/owncloud/templateeditor/pull/153
If this is the case, there is no necessity to run the pipeline of this repo on CI. 
Failure on CI is shown below
![image](https://github.com/owncloud/templateeditor/assets/64484313/aef528b9-47eb-47b8-adcc-a2b72bb41b76)

**Comment by phil-davis** [comment]
@S-Panta @saw-jan yes, please remove template editor from translation-sync CI. Make a PR and ping me for review.
