### ISSUE TITLE
Update Node.js version to (>=18.12)

### ISSUE THREAD

**Issue by PrajwolAmatya** [owncloud/translation-sync#63]
### Description
The pnpm version in web has been updated to `9.0.5` and for that at least Node.js version `18.12` is required. Currently the Node.js version being used is `16.20.2`, due to which the nightly failed with the following log:
```console
latest: Pulling from owncloudci/transifex
Digest: sha256:7d06542973077a4c9f1a1d9b5cc4ff4fc3ccdd84b5c43413ebabccfd0341c410
Status: Image is up to date for owncloudci/transifex:latest
+ cd 'web/.'
+ npm install --silent --global --force "$(jq -r '.packageManager' < package.json)";pnpm config set store-dir ./.pnpm-store;pnpm install
ERROR: This version of pnpm requires at least Node.js v18.12
The current version of Node.js is v16.20.2
Visit https://r.pnpm.io/comp to see the list of past pnpm versions with respective Node.js version support.
```

So, Node.js needs to be updated to version (>=18.12)

Related build: https://drone.owncloud.com/owncloud/translation-sync/3300

**Comment by saw-jan** [comment]
Should be fixed by https://github.com/owncloud-ci/transifex/pull/72

**Comment by phil-davis** [comment]
I merged it.

**Comment by saw-jan** [comment]
And the failing step passed in the CI: https://drone.owncloud.com/owncloud/translation-sync/3301/38/4
