### ISSUE TITLE
Transifex push is failing in `activity`, `files_antivirus` and `files_pdfviewer` app

### ISSUE THREAD

**Issue by PrajwolAmatya** [owncloud/translation-sync#64]
### Description
Similar to issue: https://github.com/owncloud/translation-sync/issues/61
Failed while pushing refs to `github.com:owncloud/activity.git`

```console
latest: Pulling from plugins/git-action
Digest: sha256:c6d438ccc784399e724a25a1a42c8bc263fce8d63b1c8a13db43fdaa7cea1b13
Status: Image is up to date for plugins/git-action:latest
+ git push origin master:master
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
remote: error: GH013: Repository rule violations found for refs/heads/master.        
remote: Review all repository rules at http://github.com/owncloud/activity/rules?ref=refs%2Fheads%2Fmaster        
remote: 
remote: - Changes must be made through a pull request.        
remote: 
To github.com:owncloud/activity.git
 ! [remote rejected] master -> master (push declined due to repository rule violations)
error: failed to push some refs to 'github.com:owncloud/activity.git'
exit status 1
```

Builds: 
- https://drone.owncloud.com/owncloud/translation-sync/3300/2/12
- https://drone.owncloud.com/owncloud/translation-sync/3302/20/12

**Comment by phil-davis** [comment]
@micbar or @DeepDiver1975 
we do not have access to the GitHub repo settings.
Who should be contact to get the settings adjusted to allow the needed access?

(discussion about what access is needed is in #61 )

**Comment by PrajwolAmatya** [comment]
Build: https://drone.owncloud.com/owncloud/translation-sync/3302/20/12
Failed on other apps as well `files_antivirus` and `files_pdfviewer`.

**Comment by phil-davis** [comment]
Failures last n ight were:
activity https://drone.owncloud.com/owncloud/translation-sync/3308/2/12
files_antivirus https://drone.owncloud.com/owncloud/translation-sync/3308/12/12
files_pdfviewer https://drone.owncloud.com/owncloud/translation-sync/3308/20/12

They are all failing because of lack of privilege to push to their GotHub repo.

@micbar (or somebody) - who should I contact to get the repo privs adjusted?

**Comment by micbar** [comment]
@phil-davis I think that i fixed them.

**Comment by phil-davis** [comment]
I will check in the coming days to see if the daily translation-sync now passes.

**Comment by phil-davis** [comment]
activity push failed:
https://github.com/owncloud/translation-sync/issues/64

files_pdfviewer push failed:
https://drone.owncloud.com/owncloud/translation-sync/3312/20/12

@DeepDiver1975 or @pako81 please can someone sort out the permissions for these.

**Comment by phil-davis** [comment]
> Found the issue for activity and files_pdfviewer

https://drone.owncloud.com/owncloud/translation-sync/3314/2/12

Passed, so closing.
